#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 0
bspc config window_gap 3
bspc config top_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# change cursor
xsetroot -cursor_name left_ptr &

# auto-reload sxhkd
echo ~/.config/sxhkd/sxhkdrc | entr -np pkill -USR1 -x sxhkd &

# fix bluetooth
# rfkill unblock bluetooth &

# launch polybar
$HOME/.config/polybar/launch.sh &

# startup
feh --bg-scale ~/backgrounds/hollowknight-transformed.jpeg &   # set wallpaper
picom --fade-in-step=1 --fade-out-step=1 --fade-delta=0 -CGb & # start picom
dunst &                                                        # start dunst

# launch workspace
bspc rule -a kitty -o desktop=^1 follow=off
st -e --hold fastfetch &
st -e --hold btop &
