preload = ~/Wallpapers/catppuccin_astronaut.png
preload = ~/Wallpapers/nord_mountain.png

wallpaper = eDP-1,~/Wallpapers/catppuccin_astronaut.png
wallpaper = HDMI-A-2,~/Wallpapers/nord_mountain.png
wallpaper = DP-3,~/Wallpapers/nord_mountain.png
wallpaper = DP-4,~/Wallpapers/nord_mountain.png

splash = false

ipc = true
